TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

INCLUDEPATH +=  \
    littlevgl_pc/lv_drivers/display/\
    littlevgl_pc/lv_drivers/indev/ \
    littlevgl_pc/lv_drivers/ \
    littlevgl_pc/lv_examples/lv_apps/benchmark/ \
    littlevgl_pc/lv_examples/lv_apps/demo/ \
    littlevgl_pc/lv_examples/lv_apps/sysmon/ \
    littlevgl_pc/lv_examples/lv_apps/terminal/ \
    littlevgl_pc/lv_examples/lv_apps/tpcal/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_group/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_misc/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_obj/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_arc/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_bar/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_btn/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_btnm/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_cb/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_chart/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_cont/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_ddlist/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_gauge/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_img/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_kb/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_label/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_led/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_line/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_list/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_lmeter/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_mbox/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_page/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_preload/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_roller/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_slider/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_sw/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_ta/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_tabview/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_win/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_stress/ \
    littlevgl_pc/lv_examples/lv_tests/lv_test_theme/ \
    littlevgl_pc/lv_examples/lv_tests/ \
    littlevgl_pc/lv_examples/lv_tutorial/0_porting/ \
    littlevgl_pc/lv_examples/lv_tutorial/10_keyboard/ \
    littlevgl_pc/lv_examples/lv_tutorial/1_hello_world/ \
    littlevgl_pc/lv_examples/lv_tutorial/2_objects/ \
    littlevgl_pc/lv_examples/lv_tutorial/3_styles/ \
    littlevgl_pc/lv_examples/lv_tutorial/4_themes/ \
    littlevgl_pc/lv_examples/lv_tutorial/5_antialiasing/ \
    littlevgl_pc/lv_examples/lv_tutorial/6_images/ \
    littlevgl_pc/lv_examples/lv_tutorial/7_fonts/ \
    littlevgl_pc/lv_examples/lv_tutorial/8_animations/ \
    littlevgl_pc/lv_examples/lv_tutorial/9_responsive/ \
    littlevgl_pc/lv_examples/ \
    littlevgl_pc/lvgl/lv_core/ \
    littlevgl_pc/lvgl/lv_draw/ \
    littlevgl_pc/lvgl/lv_fonts/ \
    littlevgl_pc/lvgl/lv_hal/ \
    littlevgl_pc/lvgl/lv_misc/ \
    littlevgl_pc/lvgl/lv_objx/ \
    littlevgl_pc/lvgl/lv_themes/ \
    littlevgl_pc/lvgl/ \
    littlevgl_pc/ \
    SDL2/


SOURCES +=  \
    littlevgl_pc/lv_drivers/display/fbdev.c \
    littlevgl_pc/lv_drivers/display/monitor.c \
    littlevgl_pc/lv_drivers/display/R61581.c \
    littlevgl_pc/lv_drivers/display/SSD1963.c \
    littlevgl_pc/lv_drivers/display/ST7565.c \
    littlevgl_pc/lv_drivers/indev/AD_touch.c \
    littlevgl_pc/lv_drivers/indev/encoder.c \
    littlevgl_pc/lv_drivers/indev/evdev.c \
    littlevgl_pc/lv_drivers/indev/FT5406EE8.c \
    littlevgl_pc/lv_drivers/indev/keyboard.c \
    littlevgl_pc/lv_drivers/indev/mouse.c \
    littlevgl_pc/lv_drivers/indev/XPT2046.c \
    littlevgl_pc/lv_examples/lv_apps/benchmark/benchmark.c \
    littlevgl_pc/lv_examples/lv_apps/benchmark/benchmark_bg.c \
    littlevgl_pc/lv_examples/lv_apps/demo/demo.c \
    littlevgl_pc/lv_examples/lv_apps/demo/img_bubble_pattern.c \
    littlevgl_pc/lv_examples/lv_apps/sysmon/sysmon.c \
    littlevgl_pc/lv_examples/lv_apps/terminal/terminal.c \
    littlevgl_pc/lv_examples/lv_apps/tpcal/tpcal.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_group/lv_test_group.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_misc/lv_test_task.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_obj/lv_test_obj.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_arc/lv_test_arc.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_bar/lv_test_bar.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_btn/lv_test_btn.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_btnm/lv_test_btnm.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_cb/lv_test_cb.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_chart/lv_test_chart.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_cont/lv_test_cont.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_ddlist/lv_test_ddlist.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_gauge/lv_test_gauge.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_img/img_flower_icon.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_img/lv_test_img.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/imgbtn_img_1.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/imgbtn_img_2.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/imgbtn_img_3.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/imgbtn_img_4.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/lv_test_imgbtn.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_kb/lv_test_kb.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_label/lv_test_label.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_led/lv_test_led.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_line/lv_test_line.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_list/lv_test_list.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_lmeter/lv_test_lmeter.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_mbox/lv_test_mbox.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_page/lv_test_page.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_preload/lv_test_preload.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_roller/lv_test_roller.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_slider/lv_test_slider.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_sw/lv_test_sw.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_ta/lv_test_ta.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_tabview/lv_test_tabview.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_win/lv_test_win.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_stress/lv_test_stress.c \
    littlevgl_pc/lv_examples/lv_tests/lv_test_theme/lv_test_theme.c \
    littlevgl_pc/lv_examples/lv_tutorial/0_porting/lv_tutorial_porting.c \
    littlevgl_pc/lv_examples/lv_tutorial/10_keyboard/lv_tutorial_keyboard.c \
    littlevgl_pc/lv_examples/lv_tutorial/1_hello_world/lv_tutorial_hello_world.c \
    littlevgl_pc/lv_examples/lv_tutorial/2_objects/lv_tutorial_objects.c \
    littlevgl_pc/lv_examples/lv_tutorial/3_styles/lv_tutorial_styles.c \
    littlevgl_pc/lv_examples/lv_tutorial/4_themes/lv_tutorial_themes.c \
    littlevgl_pc/lv_examples/lv_tutorial/5_antialiasing/apple_icon_alpha.c \
    littlevgl_pc/lv_examples/lv_tutorial/5_antialiasing/apple_icon_chroma.c \
    littlevgl_pc/lv_examples/lv_tutorial/5_antialiasing/lv_tutorial_antialiasing.c \
    littlevgl_pc/lv_examples/lv_tutorial/6_images/lv_tutorial_images.c \
    littlevgl_pc/lv_examples/lv_tutorial/6_images/red_flower.c \
    littlevgl_pc/lv_examples/lv_tutorial/7_fonts/arial_ascii_20.c \
    littlevgl_pc/lv_examples/lv_tutorial/7_fonts/arial_cyrillic_20.c \
    littlevgl_pc/lv_examples/lv_tutorial/7_fonts/arial_math_20.c \
    littlevgl_pc/lv_examples/lv_tutorial/7_fonts/lv_tutorial_fonts.c \
    littlevgl_pc/lv_examples/lv_tutorial/8_animations/lv_tutorial_animations.c \
    littlevgl_pc/lv_examples/lv_tutorial/9_responsive/lv_tutorial_responsive.c \
    littlevgl_pc/lvgl/lv_core/lv_group.c \
    littlevgl_pc/lvgl/lv_core/lv_indev.c \
    littlevgl_pc/lvgl/lv_core/lv_obj.c \
    littlevgl_pc/lvgl/lv_core/lv_refr.c \
    littlevgl_pc/lvgl/lv_core/lv_style.c \
    littlevgl_pc/lvgl/lv_core/lv_vdb.c \
    littlevgl_pc/lvgl/lv_draw/lv_draw.c \
    littlevgl_pc/lvgl/lv_draw/lv_draw_arc.c \
    littlevgl_pc/lvgl/lv_draw/lv_draw_img.c \
    littlevgl_pc/lvgl/lv_draw/lv_draw_label.c \
    littlevgl_pc/lvgl/lv_draw/lv_draw_line.c \
    littlevgl_pc/lvgl/lv_draw/lv_draw_rbasic.c \
    littlevgl_pc/lvgl/lv_draw/lv_draw_rect.c \
    littlevgl_pc/lvgl/lv_draw/lv_draw_triangle.c \
    littlevgl_pc/lvgl/lv_draw/lv_draw_vbasic.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_builtin.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_dejavu_10.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_dejavu_10_cyrillic.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_dejavu_10_latin_sup.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_dejavu_20.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_dejavu_20_cyrillic.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_dejavu_20_latin_sup.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_dejavu_30.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_dejavu_30_cyrillic.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_dejavu_30_latin_sup.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_dejavu_40.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_dejavu_40_cyrillic.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_dejavu_40_latin_sup.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_monospace_8.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_symbol_10.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_symbol_20.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_symbol_30.c \
    littlevgl_pc/lvgl/lv_fonts/lv_font_symbol_40.c \
    littlevgl_pc/lvgl/lv_hal/lv_hal_disp.c \
    littlevgl_pc/lvgl/lv_hal/lv_hal_indev.c \
    littlevgl_pc/lvgl/lv_hal/lv_hal_tick.c \
    littlevgl_pc/lvgl/lv_misc/lv_anim.c \
    littlevgl_pc/lvgl/lv_misc/lv_area.c \
    littlevgl_pc/lvgl/lv_misc/lv_circ.c \
    littlevgl_pc/lvgl/lv_misc/lv_color.c \
    littlevgl_pc/lvgl/lv_misc/lv_font.c \
    littlevgl_pc/lvgl/lv_misc/lv_fs.c \
    littlevgl_pc/lvgl/lv_misc/lv_ll.c \
    littlevgl_pc/lvgl/lv_misc/lv_log.c \
    littlevgl_pc/lvgl/lv_misc/lv_math.c \
    littlevgl_pc/lvgl/lv_misc/lv_mem.c \
    littlevgl_pc/lvgl/lv_misc/lv_task.c \
    littlevgl_pc/lvgl/lv_misc/lv_templ.c \
    littlevgl_pc/lvgl/lv_misc/lv_txt.c \
    littlevgl_pc/lvgl/lv_misc/lv_ufs.c \
    littlevgl_pc/lvgl/lv_objx/lv_arc.c \
    littlevgl_pc/lvgl/lv_objx/lv_bar.c \
    littlevgl_pc/lvgl/lv_objx/lv_btn.c \
    littlevgl_pc/lvgl/lv_objx/lv_btnm.c \
    littlevgl_pc/lvgl/lv_objx/lv_calendar.c \
    littlevgl_pc/lvgl/lv_objx/lv_cb.c \
    littlevgl_pc/lvgl/lv_objx/lv_chart.c \
    littlevgl_pc/lvgl/lv_objx/lv_cont.c \
    littlevgl_pc/lvgl/lv_objx/lv_ddlist.c \
    littlevgl_pc/lvgl/lv_objx/lv_gauge.c \
    littlevgl_pc/lvgl/lv_objx/lv_img.c \
    littlevgl_pc/lvgl/lv_objx/lv_imgbtn.c \
    littlevgl_pc/lvgl/lv_objx/lv_kb.c \
    littlevgl_pc/lvgl/lv_objx/lv_label.c \
    littlevgl_pc/lvgl/lv_objx/lv_led.c \
    littlevgl_pc/lvgl/lv_objx/lv_line.c \
    littlevgl_pc/lvgl/lv_objx/lv_list.c \
    littlevgl_pc/lvgl/lv_objx/lv_lmeter.c \
    littlevgl_pc/lvgl/lv_objx/lv_mbox.c \
    littlevgl_pc/lvgl/lv_objx/lv_objx_templ.c \
    littlevgl_pc/lvgl/lv_objx/lv_page.c \
    littlevgl_pc/lvgl/lv_objx/lv_preload.c \
    littlevgl_pc/lvgl/lv_objx/lv_roller.c \
    littlevgl_pc/lvgl/lv_objx/lv_slider.c \
    littlevgl_pc/lvgl/lv_objx/lv_sw.c \
    littlevgl_pc/lvgl/lv_objx/lv_ta.c \
    littlevgl_pc/lvgl/lv_objx/lv_tabview.c \
    littlevgl_pc/lvgl/lv_objx/lv_win.c \
    littlevgl_pc/lvgl/lv_themes/lv_theme.c \
    littlevgl_pc/lvgl/lv_themes/lv_theme_alien.c \
    littlevgl_pc/lvgl/lv_themes/lv_theme_default.c \
    littlevgl_pc/lvgl/lv_themes/lv_theme_material.c \
    littlevgl_pc/lvgl/lv_themes/lv_theme_mono.c \
    littlevgl_pc/lvgl/lv_themes/lv_theme_nemo.c \
    littlevgl_pc/lvgl/lv_themes/lv_theme_night.c \
    littlevgl_pc/lvgl/lv_themes/lv_theme_templ.c \
    littlevgl_pc/lvgl/lv_themes/lv_theme_zen.c \
    littlevgl_pc/main.c \
    littlevgl_pc/mouse_cursor_icon.c

#include(deployment.pri)
#qtcAddDeployment()


#第一种方法：格式为:  LIBS += -L+相对路径+空格+-l+库文件的名字（不加.lib）
LIBS += -L../littlevgl_qt/SDL2 -lSDL2
LIBS += -L../littlevgl_qt/SDL2 -lSDL2main
LIBS += -L../littlevgl_qt/SDL2 -lSDL2test

#第二种方法：格式为:  LIBS += -L+绝对路径+空格+-l+库文件的名字（不加.lib）
#LIBS += -LE:/CODE/QT/lib/x86 -lSDL2
#LIBS += -LE:/CODE/QT/lib/x86 -lSDL2main
#LIBS += -LE:/CODE/QT/lib/x86 -lSDL2test


#第三种方法：格式为:  LIBS += -L+相对路径++库文件的名字（加.lib）
#LIBS += -L../lib/x86/SDL2.lib
#LIBS += -L../lib/x86/SDL2main.lib
#LIBS += -L../lib/x86/SDL2test.lib

#第四种方法：
#LIBS += -L../lib/x86
#LIBS += SDL2.lib
#LIBS += SDL2main.lib
#LIBS += SDL2test.lib

INCLUDEPATH +=  \
    SDL2/   \

HEADERS += \
    littlevgl_pc/lv_drivers/display/fbdev.h \
    littlevgl_pc/lv_drivers/display/monitor.h \
    littlevgl_pc/lv_drivers/display/R61581.h \
    littlevgl_pc/lv_drivers/display/SSD1963.h \
    littlevgl_pc/lv_drivers/display/ST7565.h \
    littlevgl_pc/lv_drivers/indev/AD_touch.h \
    littlevgl_pc/lv_drivers/indev/encoder.h \
    littlevgl_pc/lv_drivers/indev/evdev.h \
    littlevgl_pc/lv_drivers/indev/FT5406EE8.h \
    littlevgl_pc/lv_drivers/indev/keyboard.h \
    littlevgl_pc/lv_drivers/indev/mouse.h \
    littlevgl_pc/lv_drivers/indev/XPT2046.h \
    littlevgl_pc/lv_drivers/lv_drv_conf_templ.h \
    littlevgl_pc/lv_examples/lv_apps/benchmark/benchmark.h \
    littlevgl_pc/lv_examples/lv_apps/demo/demo.h \
    littlevgl_pc/lv_examples/lv_apps/sysmon/sysmon.h \
    littlevgl_pc/lv_examples/lv_apps/terminal/terminal.h \
    littlevgl_pc/lv_examples/lv_apps/tpcal/tpcal.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_group/lv_test_group.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_misc/lv_test_task.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_obj/lv_test_obj.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_arc/lv_test_arc.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_bar/lv_test_bar.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_btn/lv_test_btn.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_btnm/lv_test_btnm.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_cb/lv_test_cb.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_chart/lv_test_chart.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_cont/lv_test_cont.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_ddlist/lv_test_ddlist.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_gauge/lv_test_gauge.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_img/lv_test_img.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_imgbtn/lv_test_imgbtn.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_kb/lv_test_kb.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_label/lv_test_label.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_led/lv_test_led.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_line/lv_test_line.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_list/lv_test_list.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_lmeter/lv_test_lmeter.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_mbox/lv_test_mbox.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_page/lv_test_page.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_preload/lv_test_preload.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_roller/lv_test_roller.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_slider/lv_test_slider.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_sw/lv_test_sw.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_ta/lv_test_ta.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_tabview/lv_test_tabview.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_objx/lv_test_win/lv_test_win.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_stress/lv_test_stress.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test_theme/lv_test_theme.h \
    littlevgl_pc/lv_examples/lv_tests/lv_test.h \
    littlevgl_pc/lv_examples/lv_tutorial/0_porting/lv_tutorial_porting.h \
    littlevgl_pc/lv_examples/lv_tutorial/10_keyboard/lv_tutorial_keyboard.h \
    littlevgl_pc/lv_examples/lv_tutorial/1_hello_world/lv_tutorial_hello_world.h \
    littlevgl_pc/lv_examples/lv_tutorial/2_objects/lv_tutorial_objects.h \
    littlevgl_pc/lv_examples/lv_tutorial/3_styles/lv_tutorial_styles.h \
    littlevgl_pc/lv_examples/lv_tutorial/4_themes/lv_tutorial_themes.h \
    littlevgl_pc/lv_examples/lv_tutorial/5_antialiasing/lv_tutorial_antialiasing.h \
    littlevgl_pc/lv_examples/lv_tutorial/6_images/lv_tutorial_images.h \
    littlevgl_pc/lv_examples/lv_tutorial/7_fonts/lv_tutorial_fonts.h \
    littlevgl_pc/lv_examples/lv_tutorial/8_animations/lv_tutorial_animations.h \
    littlevgl_pc/lv_examples/lv_tutorial/9_responsive/lv_tutorial_responsive.h \
    littlevgl_pc/lv_examples/lv_ex_conf_templ.h \
    littlevgl_pc/lv_examples/lv_examples.h \
    littlevgl_pc/lvgl/lv_core/lv_group.h \
    littlevgl_pc/lvgl/lv_core/lv_indev.h \
    littlevgl_pc/lvgl/lv_core/lv_obj.h \
    littlevgl_pc/lvgl/lv_core/lv_refr.h \
    littlevgl_pc/lvgl/lv_core/lv_style.h \
    littlevgl_pc/lvgl/lv_core/lv_vdb.h \
    littlevgl_pc/lvgl/lv_draw/lv_draw.h \
    littlevgl_pc/lvgl/lv_draw/lv_draw_arc.h \
    littlevgl_pc/lvgl/lv_draw/lv_draw_img.h \
    littlevgl_pc/lvgl/lv_draw/lv_draw_label.h \
    littlevgl_pc/lvgl/lv_draw/lv_draw_line.h \
    littlevgl_pc/lvgl/lv_draw/lv_draw_rbasic.h \
    littlevgl_pc/lvgl/lv_draw/lv_draw_rect.h \
    littlevgl_pc/lvgl/lv_draw/lv_draw_triangle.h \
    littlevgl_pc/lvgl/lv_draw/lv_draw_vbasic.h \
    littlevgl_pc/lvgl/lv_fonts/lv_font_builtin.h \
    littlevgl_pc/lvgl/lv_hal/lv_hal.h \
    littlevgl_pc/lvgl/lv_hal/lv_hal_disp.h \
    littlevgl_pc/lvgl/lv_hal/lv_hal_indev.h \
    littlevgl_pc/lvgl/lv_hal/lv_hal_tick.h \
    littlevgl_pc/lvgl/lv_misc/lv_anim.h \
    littlevgl_pc/lvgl/lv_misc/lv_area.h \
    littlevgl_pc/lvgl/lv_misc/lv_circ.h \
    littlevgl_pc/lvgl/lv_misc/lv_color.h \
    littlevgl_pc/lvgl/lv_misc/lv_font.h \
    littlevgl_pc/lvgl/lv_misc/lv_fs.h \
    littlevgl_pc/lvgl/lv_misc/lv_ll.h \
    littlevgl_pc/lvgl/lv_misc/lv_log.h \
    littlevgl_pc/lvgl/lv_misc/lv_math.h \
    littlevgl_pc/lvgl/lv_misc/lv_mem.h \
    littlevgl_pc/lvgl/lv_misc/lv_symbol_def.h \
    littlevgl_pc/lvgl/lv_misc/lv_task.h \
    littlevgl_pc/lvgl/lv_misc/lv_templ.h \
    littlevgl_pc/lvgl/lv_misc/lv_txt.h \
    littlevgl_pc/lvgl/lv_misc/lv_ufs.h \
    littlevgl_pc/lvgl/lv_objx/lv_arc.h \
    littlevgl_pc/lvgl/lv_objx/lv_bar.h \
    littlevgl_pc/lvgl/lv_objx/lv_btn.h \
    littlevgl_pc/lvgl/lv_objx/lv_btnm.h \
    littlevgl_pc/lvgl/lv_objx/lv_calendar.h \
    littlevgl_pc/lvgl/lv_objx/lv_cb.h \
    littlevgl_pc/lvgl/lv_objx/lv_chart.h \
    littlevgl_pc/lvgl/lv_objx/lv_cont.h \
    littlevgl_pc/lvgl/lv_objx/lv_ddlist.h \
    littlevgl_pc/lvgl/lv_objx/lv_gauge.h \
    littlevgl_pc/lvgl/lv_objx/lv_img.h \
    littlevgl_pc/lvgl/lv_objx/lv_imgbtn.h \
    littlevgl_pc/lvgl/lv_objx/lv_kb.h \
    littlevgl_pc/lvgl/lv_objx/lv_label.h \
    littlevgl_pc/lvgl/lv_objx/lv_led.h \
    littlevgl_pc/lvgl/lv_objx/lv_line.h \
    littlevgl_pc/lvgl/lv_objx/lv_list.h \
    littlevgl_pc/lvgl/lv_objx/lv_lmeter.h \
    littlevgl_pc/lvgl/lv_objx/lv_mbox.h \
    littlevgl_pc/lvgl/lv_objx/lv_objx_templ.h \
    littlevgl_pc/lvgl/lv_objx/lv_page.h \
    littlevgl_pc/lvgl/lv_objx/lv_preload.h \
    littlevgl_pc/lvgl/lv_objx/lv_roller.h \
    littlevgl_pc/lvgl/lv_objx/lv_slider.h \
    littlevgl_pc/lvgl/lv_objx/lv_sw.h \
    littlevgl_pc/lvgl/lv_objx/lv_ta.h \
    littlevgl_pc/lvgl/lv_objx/lv_tabview.h \
    littlevgl_pc/lvgl/lv_objx/lv_win.h \
    littlevgl_pc/lvgl/lv_themes/lv_theme.h \
    littlevgl_pc/lvgl/lv_themes/lv_theme_alien.h \
    littlevgl_pc/lvgl/lv_themes/lv_theme_default.h \
    littlevgl_pc/lvgl/lv_themes/lv_theme_material.h \
    littlevgl_pc/lvgl/lv_themes/lv_theme_mono.h \
    littlevgl_pc/lvgl/lv_themes/lv_theme_nemo.h \
    littlevgl_pc/lvgl/lv_themes/lv_theme_night.h \
    littlevgl_pc/lvgl/lv_themes/lv_theme_templ.h \
    littlevgl_pc/lvgl/lv_themes/lv_theme_zen.h \
    littlevgl_pc/lvgl/lv_conf_templ.h \
    littlevgl_pc/lvgl/lvgl.h \
    littlevgl_pc/lv_conf.h \
    littlevgl_pc/lv_drv_conf.h \
    littlevgl_pc/lv_ex_conf.h \
    SDL2/begin_code.h \
    SDL2/close_code.h \
    SDL2/SDL.h \
    SDL2/SDL_assert.h \
    SDL2/SDL_atomic.h \
    SDL2/SDL_audio.h \
    SDL2/SDL_bits.h \
    SDL2/SDL_blendmode.h \
    SDL2/SDL_clipboard.h \
    SDL2/SDL_config.h \
    SDL2/SDL_cpuinfo.h \
    SDL2/SDL_endian.h \
    SDL2/SDL_error.h \
    SDL2/SDL_events.h \
    SDL2/SDL_filesystem.h \
    SDL2/SDL_gamecontroller.h \
    SDL2/SDL_gesture.h \
    SDL2/SDL_haptic.h \
    SDL2/SDL_hints.h \
    SDL2/SDL_joystick.h \
    SDL2/SDL_keyboard.h \
    SDL2/SDL_keycode.h \
    SDL2/SDL_loadso.h \
    SDL2/SDL_log.h \
    SDL2/SDL_main.h \
    SDL2/SDL_messagebox.h \
    SDL2/SDL_mouse.h \
    SDL2/SDL_mutex.h \
    SDL2/SDL_name.h \
    SDL2/SDL_opengl.h \
    SDL2/SDL_opengles.h \
    SDL2/SDL_opengles2.h \
    SDL2/SDL_pixels.h \
    SDL2/SDL_platform.h \
    SDL2/SDL_power.h \
    SDL2/SDL_quit.h \
    SDL2/SDL_rect.h \
    SDL2/SDL_render.h \
    SDL2/SDL_revision.h \
    SDL2/SDL_rwops.h \
    SDL2/SDL_scancode.h \
    SDL2/SDL_shape.h \
    SDL2/SDL_stdinc.h \
    SDL2/SDL_surface.h \
    SDL2/SDL_system.h \
    SDL2/SDL_syswm.h \
    SDL2/SDL_test.h \
    SDL2/SDL_test_assert.h \
    SDL2/SDL_test_common.h \
    SDL2/SDL_test_compare.h \
    SDL2/SDL_test_crc32.h \
    SDL2/SDL_test_font.h \
    SDL2/SDL_test_fuzzer.h \
    SDL2/SDL_test_harness.h \
    SDL2/SDL_test_images.h \
    SDL2/SDL_test_log.h \
    SDL2/SDL_test_md5.h \
    SDL2/SDL_test_random.h \
    SDL2/SDL_thread.h \
    SDL2/SDL_timer.h \
    SDL2/SDL_touch.h \
    SDL2/SDL_types.h \
    SDL2/SDL_version.h \
    SDL2/SDL_video.h
